// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.0a
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:375


#include "Event_ForwarderC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "Event_ForwarderC.inl"
#endif /* !defined INLINE */

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_cs.cpp:53

// Traits specializations for Event_Forwarder::StructuredProxyPushSupplier.

Event_Forwarder::StructuredProxyPushSupplier_ptr
TAO::Objref_Traits<Event_Forwarder::StructuredProxyPushSupplier>::duplicate (
    Event_Forwarder::StructuredProxyPushSupplier_ptr p)
{
  return Event_Forwarder::StructuredProxyPushSupplier::_duplicate (p);
}

void
TAO::Objref_Traits<Event_Forwarder::StructuredProxyPushSupplier>::release (
    Event_Forwarder::StructuredProxyPushSupplier_ptr p)
{
  ::CORBA::release (p);
}

Event_Forwarder::StructuredProxyPushSupplier_ptr
TAO::Objref_Traits<Event_Forwarder::StructuredProxyPushSupplier>::nil (void)
{
  return Event_Forwarder::StructuredProxyPushSupplier::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Event_Forwarder::StructuredProxyPushSupplier>::marshal (
    const Event_Forwarder::StructuredProxyPushSupplier_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*Event_Forwarder__TAO_StructuredProxyPushSupplier_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj) = 0;

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:80

void
Event_Forwarder::StructuredProxyPushSupplier::forward_structured (
  const ::CosNotification::StructuredEvent & event)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_StructuredProxyPushSupplier_Proxy_Broker_ == 0)
    {
      Event_Forwarder_StructuredProxyPushSupplier_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CosNotification::StructuredEvent>::in_arg_val _tao_event (event);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_event
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "forward_structured",
      18,
      this->the_TAO_StructuredProxyPushSupplier_Proxy_Broker_
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:80

void
Event_Forwarder::StructuredProxyPushSupplier::forward_structured_no_filtering (
  const ::CosNotification::StructuredEvent & event)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_StructuredProxyPushSupplier_Proxy_Broker_ == 0)
    {
      Event_Forwarder_StructuredProxyPushSupplier_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CosNotification::StructuredEvent>::in_arg_val _tao_event (event);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_event
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "forward_structured_no_filtering",
      31,
      this->the_TAO_StructuredProxyPushSupplier_Proxy_Broker_
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:80

void
Event_Forwarder::StructuredProxyPushSupplier::forward_any (
  const ::CORBA::Any & event)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_StructuredProxyPushSupplier_Proxy_Broker_ == 0)
    {
      Event_Forwarder_StructuredProxyPushSupplier_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Any>::in_arg_val _tao_event (event);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_event
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "forward_any",
      11,
      this->the_TAO_StructuredProxyPushSupplier_Proxy_Broker_
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:80

void
Event_Forwarder::StructuredProxyPushSupplier::forward_any_no_filtering (
  const ::CORBA::Any & event)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_StructuredProxyPushSupplier_Proxy_Broker_ == 0)
    {
      Event_Forwarder_StructuredProxyPushSupplier_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Any>::in_arg_val _tao_event (event);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_event
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "forward_any_no_filtering",
      24,
      this->the_TAO_StructuredProxyPushSupplier_Proxy_Broker_
    );

  _tao_call.invoke (0, 0);
}

Event_Forwarder::StructuredProxyPushSupplier::StructuredProxyPushSupplier (void)
 : the_TAO_StructuredProxyPushSupplier_Proxy_Broker_ (0)
{
  this->Event_Forwarder_StructuredProxyPushSupplier_setup_collocation ();
}

void
Event_Forwarder::StructuredProxyPushSupplier::Event_Forwarder_StructuredProxyPushSupplier_setup_collocation ()
{
  if (::Event_Forwarder__TAO_StructuredProxyPushSupplier_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_StructuredProxyPushSupplier_Proxy_Broker_ =
        ::Event_Forwarder__TAO_StructuredProxyPushSupplier_Proxy_Broker_Factory_function_pointer (this);
    }
  
  this->CosNotifyChannelAdmin_StructuredProxyPushSupplier_setup_collocation ();
}

Event_Forwarder::StructuredProxyPushSupplier::~StructuredProxyPushSupplier (void)
{}

void 
Event_Forwarder::StructuredProxyPushSupplier::_tao_any_destructor (void *_tao_void_pointer)
{
  StructuredProxyPushSupplier *_tao_tmp_pointer =
    static_cast<StructuredProxyPushSupplier *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

Event_Forwarder::StructuredProxyPushSupplier_ptr
Event_Forwarder::StructuredProxyPushSupplier::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<StructuredProxyPushSupplier>::narrow (
        _tao_objref,
        "IDL:Event_Forwarder/StructuredProxyPushSupplier:1.0",
        Event_Forwarder__TAO_StructuredProxyPushSupplier_Proxy_Broker_Factory_function_pointer
      );
}

Event_Forwarder::StructuredProxyPushSupplier_ptr
Event_Forwarder::StructuredProxyPushSupplier::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<StructuredProxyPushSupplier>::unchecked_narrow (
        _tao_objref,
        "IDL:Event_Forwarder/StructuredProxyPushSupplier:1.0",
        Event_Forwarder__TAO_StructuredProxyPushSupplier_Proxy_Broker_Factory_function_pointer
      );
}

Event_Forwarder::StructuredProxyPushSupplier_ptr
Event_Forwarder::StructuredProxyPushSupplier::_nil (void)
{
  return 0;
}

Event_Forwarder::StructuredProxyPushSupplier_ptr
Event_Forwarder::StructuredProxyPushSupplier::_duplicate (StructuredProxyPushSupplier_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
Event_Forwarder::StructuredProxyPushSupplier::_tao_release (StructuredProxyPushSupplier_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Event_Forwarder::StructuredProxyPushSupplier::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotification/QoSAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyFilter/FilterAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyChannelAdmin/ProxySupplier:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyComm/NotifySubscribe:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyComm/StructuredPushSupplier:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyChannelAdmin/StructuredProxyPushSupplier:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Event_Forwarder/StructuredProxyPushSupplier:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* Event_Forwarder::StructuredProxyPushSupplier::_interface_repository_id (void) const
{
  return "IDL:Event_Forwarder/StructuredProxyPushSupplier:1.0";
}

::CORBA::Boolean
Event_Forwarder::StructuredProxyPushSupplier::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/objref_typecode.cpp:70

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_Event_Forwarder_StructuredProxyPushSupplier (
    ::CORBA::tk_objref,
    "IDL:Event_Forwarder/StructuredProxyPushSupplier:1.0",
    "StructuredProxyPushSupplier");
  

namespace Event_Forwarder
{
  ::CORBA::TypeCode_ptr const _tc_StructuredProxyPushSupplier =
    &_tao_tc_Event_Forwarder_StructuredProxyPushSupplier;
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_cs.cpp:53

// Traits specializations for Event_Forwarder::ProxyPushSupplier.

Event_Forwarder::ProxyPushSupplier_ptr
TAO::Objref_Traits<Event_Forwarder::ProxyPushSupplier>::duplicate (
    Event_Forwarder::ProxyPushSupplier_ptr p)
{
  return Event_Forwarder::ProxyPushSupplier::_duplicate (p);
}

void
TAO::Objref_Traits<Event_Forwarder::ProxyPushSupplier>::release (
    Event_Forwarder::ProxyPushSupplier_ptr p)
{
  ::CORBA::release (p);
}

Event_Forwarder::ProxyPushSupplier_ptr
TAO::Objref_Traits<Event_Forwarder::ProxyPushSupplier>::nil (void)
{
  return Event_Forwarder::ProxyPushSupplier::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Event_Forwarder::ProxyPushSupplier>::marshal (
    const Event_Forwarder::ProxyPushSupplier_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*Event_Forwarder__TAO_ProxyPushSupplier_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj) = 0;

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:80

void
Event_Forwarder::ProxyPushSupplier::forward_structured (
  const ::CosNotification::StructuredEvent & event)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_ProxyPushSupplier_Proxy_Broker_ == 0)
    {
      Event_Forwarder_ProxyPushSupplier_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CosNotification::StructuredEvent>::in_arg_val _tao_event (event);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_event
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "forward_structured",
      18,
      this->the_TAO_ProxyPushSupplier_Proxy_Broker_
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:80

void
Event_Forwarder::ProxyPushSupplier::forward_structured_no_filtering (
  const ::CosNotification::StructuredEvent & event)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_ProxyPushSupplier_Proxy_Broker_ == 0)
    {
      Event_Forwarder_ProxyPushSupplier_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CosNotification::StructuredEvent>::in_arg_val _tao_event (event);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_event
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "forward_structured_no_filtering",
      31,
      this->the_TAO_ProxyPushSupplier_Proxy_Broker_
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:80

void
Event_Forwarder::ProxyPushSupplier::forward_any (
  const ::CORBA::Any & event)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_ProxyPushSupplier_Proxy_Broker_ == 0)
    {
      Event_Forwarder_ProxyPushSupplier_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Any>::in_arg_val _tao_event (event);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_event
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "forward_any",
      11,
      this->the_TAO_ProxyPushSupplier_Proxy_Broker_
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:80

void
Event_Forwarder::ProxyPushSupplier::forward_any_no_filtering (
  const ::CORBA::Any & event)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_ProxyPushSupplier_Proxy_Broker_ == 0)
    {
      Event_Forwarder_ProxyPushSupplier_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Any>::in_arg_val _tao_event (event);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_event
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "forward_any_no_filtering",
      24,
      this->the_TAO_ProxyPushSupplier_Proxy_Broker_
    );

  _tao_call.invoke (0, 0);
}

Event_Forwarder::ProxyPushSupplier::ProxyPushSupplier (void)
 : the_TAO_ProxyPushSupplier_Proxy_Broker_ (0)
{
  this->Event_Forwarder_ProxyPushSupplier_setup_collocation ();
}

void
Event_Forwarder::ProxyPushSupplier::Event_Forwarder_ProxyPushSupplier_setup_collocation ()
{
  if (::Event_Forwarder__TAO_ProxyPushSupplier_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_ProxyPushSupplier_Proxy_Broker_ =
        ::Event_Forwarder__TAO_ProxyPushSupplier_Proxy_Broker_Factory_function_pointer (this);
    }
  
  this->CosNotifyChannelAdmin_ProxyPushSupplier_setup_collocation ();
}

Event_Forwarder::ProxyPushSupplier::~ProxyPushSupplier (void)
{}

void 
Event_Forwarder::ProxyPushSupplier::_tao_any_destructor (void *_tao_void_pointer)
{
  ProxyPushSupplier *_tao_tmp_pointer =
    static_cast<ProxyPushSupplier *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

Event_Forwarder::ProxyPushSupplier_ptr
Event_Forwarder::ProxyPushSupplier::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<ProxyPushSupplier>::narrow (
        _tao_objref,
        "IDL:Event_Forwarder/ProxyPushSupplier:1.0",
        Event_Forwarder__TAO_ProxyPushSupplier_Proxy_Broker_Factory_function_pointer
      );
}

Event_Forwarder::ProxyPushSupplier_ptr
Event_Forwarder::ProxyPushSupplier::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<ProxyPushSupplier>::unchecked_narrow (
        _tao_objref,
        "IDL:Event_Forwarder/ProxyPushSupplier:1.0",
        Event_Forwarder__TAO_ProxyPushSupplier_Proxy_Broker_Factory_function_pointer
      );
}

Event_Forwarder::ProxyPushSupplier_ptr
Event_Forwarder::ProxyPushSupplier::_nil (void)
{
  return 0;
}

Event_Forwarder::ProxyPushSupplier_ptr
Event_Forwarder::ProxyPushSupplier::_duplicate (ProxyPushSupplier_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
Event_Forwarder::ProxyPushSupplier::_tao_release (ProxyPushSupplier_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Event_Forwarder::ProxyPushSupplier::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotification/QoSAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyFilter/FilterAdmin:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyChannelAdmin/ProxySupplier:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyComm/NotifySubscribe:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosEventComm/PushSupplier:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyComm/PushSupplier:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CosNotifyChannelAdmin/ProxyPushSupplier:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Event_Forwarder/ProxyPushSupplier:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* Event_Forwarder::ProxyPushSupplier::_interface_repository_id (void) const
{
  return "IDL:Event_Forwarder/ProxyPushSupplier:1.0";
}

::CORBA::Boolean
Event_Forwarder::ProxyPushSupplier::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/objref_typecode.cpp:70

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_Event_Forwarder_ProxyPushSupplier (
    ::CORBA::tk_objref,
    "IDL:Event_Forwarder/ProxyPushSupplier:1.0",
    "ProxyPushSupplier");
  

namespace Event_Forwarder
{
  ::CORBA::TypeCode_ptr const _tc_ProxyPushSupplier =
    &_tao_tc_Event_Forwarder_ProxyPushSupplier;
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/any_op_cs.cpp:46

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<Event_Forwarder::StructuredProxyPushSupplier>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Event_Forwarder
{
  

  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      StructuredProxyPushSupplier_ptr _tao_elem)
  {
    StructuredProxyPushSupplier_ptr _tao_objptr =
      StructuredProxyPushSupplier::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }

  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      StructuredProxyPushSupplier_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<StructuredProxyPushSupplier>::insert (
        _tao_any,
        StructuredProxyPushSupplier::_tao_any_destructor,
        _tc_StructuredProxyPushSupplier,
        *_tao_elem);
  }

  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      StructuredProxyPushSupplier_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<StructuredProxyPushSupplier>::extract (
          _tao_any,
          StructuredProxyPushSupplier::_tao_any_destructor,
          _tc_StructuredProxyPushSupplier,
          _tao_elem);
  }
}

#else


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Event_Forwarder::StructuredProxyPushSupplier_ptr _tao_elem)
{
  Event_Forwarder::StructuredProxyPushSupplier_ptr _tao_objptr =
    Event_Forwarder::StructuredProxyPushSupplier::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Event_Forwarder::StructuredProxyPushSupplier_ptr *_tao_elem)
{
  TAO::Any_Impl_T<Event_Forwarder::StructuredProxyPushSupplier>::insert (
      _tao_any,
      Event_Forwarder::StructuredProxyPushSupplier::_tao_any_destructor,
      Event_Forwarder::_tc_StructuredProxyPushSupplier,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    Event_Forwarder::StructuredProxyPushSupplier_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<Event_Forwarder::StructuredProxyPushSupplier>::extract (
        _tao_any,
        Event_Forwarder::StructuredProxyPushSupplier::_tao_any_destructor,
        Event_Forwarder::_tc_StructuredProxyPushSupplier,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/any_op_cs.cpp:46

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<Event_Forwarder::ProxyPushSupplier>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Event_Forwarder
{
  

  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      ProxyPushSupplier_ptr _tao_elem)
  {
    ProxyPushSupplier_ptr _tao_objptr =
      ProxyPushSupplier::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }

  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      ProxyPushSupplier_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<ProxyPushSupplier>::insert (
        _tao_any,
        ProxyPushSupplier::_tao_any_destructor,
        _tc_ProxyPushSupplier,
        *_tao_elem);
  }

  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      ProxyPushSupplier_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<ProxyPushSupplier>::extract (
          _tao_any,
          ProxyPushSupplier::_tao_any_destructor,
          _tc_ProxyPushSupplier,
          _tao_elem);
  }
}

#else


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Event_Forwarder::ProxyPushSupplier_ptr _tao_elem)
{
  Event_Forwarder::ProxyPushSupplier_ptr _tao_objptr =
    Event_Forwarder::ProxyPushSupplier::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Event_Forwarder::ProxyPushSupplier_ptr *_tao_elem)
{
  TAO::Any_Impl_T<Event_Forwarder::ProxyPushSupplier>::insert (
      _tao_any,
      Event_Forwarder::ProxyPushSupplier::_tao_any_destructor,
      Event_Forwarder::_tc_ProxyPushSupplier,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    Event_Forwarder::ProxyPushSupplier_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<Event_Forwarder::ProxyPushSupplier>::extract (
        _tao_any,
        Event_Forwarder::ProxyPushSupplier::_tao_any_destructor,
        Event_Forwarder::_tc_ProxyPushSupplier,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/cdr_op_cs.cpp:53


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Event_Forwarder::StructuredProxyPushSupplier_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Event_Forwarder::StructuredProxyPushSupplier_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::Event_Forwarder::StructuredProxyPushSupplier RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        Event_Forwarder__TAO_StructuredProxyPushSupplier_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/cdr_op_cs.cpp:53


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Event_Forwarder::ProxyPushSupplier_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Event_Forwarder::ProxyPushSupplier_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::Event_Forwarder::ProxyPushSupplier RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        Event_Forwarder__TAO_ProxyPushSupplier_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL





TAO_END_VERSIONED_NAMESPACE_DECL


