// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.0a
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:150

#ifndef _TAO_IDL_FT_CORBAC_IZVFPI_H_
#define _TAO_IDL_FT_CORBAC_IZVFPI_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "orbsvcs/FaultTolerance/fault_tol_export.h"
#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/UserException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/AnyTypeCode/TypeCode.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "orbsvcs/FT_CORBA_ORBC.h"
#include "orbsvcs/PortableGroupC.h"
#include "orbsvcs/CosNamingC.h"
#include "orbsvcs/CosNotificationC.h"
#include "orbsvcs/CosNotifyFilterC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 0 || TAO_BETA_VERSION != 4
#error This file should be regenerated with TAO_IDL from version 2.0a
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO TAO_FT_Export

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from 
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_root/root_ch.cpp:162

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  class Collocation_Proxy_Broker;
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_module/module_ch.cpp:41

namespace FT
{

  // TAO_IDL - Generated from
  // .\be\be_interface.cpp:784

#if !defined (_FT_FAULTNOTIFIER__VAR_OUT_CH_)
#define _FT_FAULTNOTIFIER__VAR_OUT_CH_

  class FaultNotifier;
  typedef FaultNotifier *FaultNotifier_ptr;

  typedef
    TAO_Objref_Var_T<
        FaultNotifier
      >
    FaultNotifier_var;
  
  typedef
    TAO_Objref_Out_T<
        FaultNotifier
      >
    FaultNotifier_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:369

  typedef ::CORBA::Long ReplicationStyleValue;
  typedef ::CORBA::Long_out ReplicationStyleValue_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_ReplicationStyleValue;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long STATELESS = 0;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long COLD_PASSIVE = 1;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long WARM_PASSIVE = 2;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long ACTIVE = 3;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long ACTIVE_WITH_VOTING = 4;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long SEMI_ACTIVE = 5;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:369

  typedef ::CORBA::Long ConsistencyStyleValue;
  typedef ::CORBA::Long_out ConsistencyStyleValue_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_ConsistencyStyleValue;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long CONS_APP_CTRL = 0;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long CONS_INF_CTRL = 1;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:369

  typedef ::CORBA::Long FaultMonitoringStyleValue;
  typedef ::CORBA::Long_out FaultMonitoringStyleValue_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_FaultMonitoringStyleValue;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long PULL = 0;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long PUSH = 1;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long NOT_MONITORED = 2;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:369

  typedef ::CORBA::Long FaultMonitoringGranularityValue;
  typedef ::CORBA::Long_out FaultMonitoringGranularityValue_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_FaultMonitoringGranularityValue;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long MEMB = 0;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long LOC = 1;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long LOC_AND_TYPE = 2;

  // TAO_IDL - Generated from
  // .\be\be_type.cpp:261

  struct FaultMonitoringIntervalAndTimeoutValue;

  typedef
    ::TAO_Fixed_Var_T<
        FaultMonitoringIntervalAndTimeoutValue
      >
    FaultMonitoringIntervalAndTimeoutValue_var;
  
  typedef
    FaultMonitoringIntervalAndTimeoutValue &
    FaultMonitoringIntervalAndTimeoutValue_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_structure/structure_ch.cpp:49

  struct TAO_FT_Export FaultMonitoringIntervalAndTimeoutValue
  {

    // TAO_IDL - Generated from
    // .\be\be_type.cpp:307
    
    typedef FaultMonitoringIntervalAndTimeoutValue_var _var_type;
    typedef FaultMonitoringIntervalAndTimeoutValue_out _out_type;

    static void _tao_any_destructor (void *);
    
    TimeBase::TimeT monitoring_interval;
    TimeBase::TimeT timeout;
  };

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_FaultMonitoringIntervalAndTimeoutValue;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_exception/exception_ch.cpp:43

  class TAO_FT_Export BadReplicationStyle : public ::CORBA::UserException
  {
  public:
    
    BadReplicationStyle (void);
    BadReplicationStyle (const BadReplicationStyle &);
    ~BadReplicationStyle (void);

    BadReplicationStyle &operator= (const BadReplicationStyle &);

    static void _tao_any_destructor (void *);

    static BadReplicationStyle *_downcast ( ::CORBA::Exception *);
    static const BadReplicationStyle *_downcast ( ::CORBA::Exception const *);

    static ::CORBA::Exception *_alloc (void);

    virtual ::CORBA::Exception *_tao_duplicate (void) const;

    virtual void _raise (void) const;

    virtual void _tao_encode (TAO_OutputCDR &cdr) const;
    virtual void _tao_decode (TAO_InputCDR &cdr);
    

    virtual ::CORBA::TypeCode_ptr _tao_type (void) const;
  };

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_BadReplicationStyle;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_exception/exception_ch.cpp:43

  class TAO_FT_Export PrimaryNotSet : public ::CORBA::UserException
  {
  public:
    
    PrimaryNotSet (void);
    PrimaryNotSet (const PrimaryNotSet &);
    ~PrimaryNotSet (void);

    PrimaryNotSet &operator= (const PrimaryNotSet &);

    static void _tao_any_destructor (void *);

    static PrimaryNotSet *_downcast ( ::CORBA::Exception *);
    static const PrimaryNotSet *_downcast ( ::CORBA::Exception const *);

    static ::CORBA::Exception *_alloc (void);

    virtual ::CORBA::Exception *_tao_duplicate (void) const;

    virtual void _raise (void) const;

    virtual void _tao_encode (TAO_OutputCDR &cdr) const;
    virtual void _tao_decode (TAO_InputCDR &cdr);
    

    virtual ::CORBA::TypeCode_ptr _tao_type (void) const;
  };

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_PrimaryNotSet;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:403

  typedef char * TypeId;
  typedef ::CORBA::String_var TypeId_var;
  typedef ::CORBA::String_out TypeId_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_TypeId;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:369

  typedef PortableGroup::ObjectGroup ObjectGroup;
  typedef PortableGroup::ObjectGroup_ptr ObjectGroup_ptr;
  typedef PortableGroup::ObjectGroup_var ObjectGroup_var;
  typedef PortableGroup::ObjectGroup_out ObjectGroup_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_ObjectGroup;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:462

  typedef PortableGroup::Name Name;
  typedef PortableGroup::Name_var Name_var;
  typedef PortableGroup::Name_out Name_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_Name;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:369

  typedef PortableGroup::Value Value;
  typedef PortableGroup::Value_ptr Value_ptr;
  typedef PortableGroup::Value_var Value_var;
  typedef PortableGroup::Value_out Value_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_Value;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:509

  typedef PortableGroup::Property Property;
  typedef PortableGroup::Property_var Property_var;
  typedef PortableGroup::Property_out Property_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_Property;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:462

  typedef PortableGroup::Properties Properties;
  typedef PortableGroup::Properties_var Properties_var;
  typedef PortableGroup::Properties_out Properties_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_Properties;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:462

  typedef PortableGroup::Location Location;
  typedef PortableGroup::Location_var Location_var;
  typedef PortableGroup::Location_out Location_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_Location;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:462

  typedef PortableGroup::Locations Locations;
  typedef PortableGroup::Locations_var Locations_var;
  typedef PortableGroup::Locations_out Locations_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_Locations;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:462

  typedef PortableGroup::Criteria Criteria;
  typedef PortableGroup::Criteria_var Criteria_var;
  typedef PortableGroup::Criteria_out Criteria_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_Criteria;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:509

  typedef PortableGroup::FactoryInfo FactoryInfo;
  typedef PortableGroup::FactoryInfo_var FactoryInfo_var;
  typedef PortableGroup::FactoryInfo_out FactoryInfo_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_FactoryInfo;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:462

  typedef PortableGroup::FactoryInfos FactoryInfos;
  typedef PortableGroup::FactoryInfos_var FactoryInfos_var;
  typedef PortableGroup::FactoryInfos_out FactoryInfos_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_FactoryInfos;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:369

  typedef PortableGroup::MembershipStyleValue MembershipStyleValue;
  typedef PortableGroup::MembershipStyleValue_out MembershipStyleValue_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_MembershipStyleValue;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:462

  typedef PortableGroup::FactoriesValue FactoriesValue;
  typedef PortableGroup::FactoriesValue_var FactoriesValue_var;
  typedef PortableGroup::FactoriesValue_out FactoriesValue_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_FactoriesValue;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:369

  typedef PortableGroup::InitialNumberMembersValue InitialNumberMembersValue;
  typedef PortableGroup::InitialNumberMembersValue_out InitialNumberMembersValue_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_InitialNumberMembersValue;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:369

  typedef PortableGroup::MinimumNumberMembersValue MinimumNumberMembersValue;
  typedef PortableGroup::MinimumNumberMembersValue_out MinimumNumberMembersValue_out;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_MinimumNumberMembersValue;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:320

  typedef PortableGroup::PropertyManager PropertyManager;
  typedef PortableGroup::PropertyManager_ptr PropertyManager_ptr;
  typedef PortableGroup::PropertyManager_var PropertyManager_var;
  typedef PortableGroup::PropertyManager_out PropertyManager_out;
  

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_PropertyManager;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:320

  typedef PortableGroup::ObjectGroupManager ObjectGroupManager;
  typedef PortableGroup::ObjectGroupManager_ptr ObjectGroupManager_ptr;
  typedef PortableGroup::ObjectGroupManager_var ObjectGroupManager_var;
  typedef PortableGroup::ObjectGroupManager_out ObjectGroupManager_out;
  

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_ObjectGroupManager;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typedef/typedef_ch.cpp:320

  typedef PortableGroup::GenericFactory GenericFactory;
  typedef PortableGroup::GenericFactory_ptr GenericFactory_ptr;
  typedef PortableGroup::GenericFactory_var GenericFactory_var;
  typedef PortableGroup::GenericFactory_out GenericFactory_out;
  

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_GenericFactory;

  // TAO_IDL - Generated from
  // .\be\be_interface.cpp:784

#if !defined (_FT_FTOBJECTGROUPMANAGER__VAR_OUT_CH_)
#define _FT_FTOBJECTGROUPMANAGER__VAR_OUT_CH_

  class FTObjectGroupManager;
  typedef FTObjectGroupManager *FTObjectGroupManager_ptr;

  typedef
    TAO_Objref_Var_T<
        FTObjectGroupManager
      >
    FTObjectGroupManager_var;
  
  typedef
    TAO_Objref_Out_T<
        FTObjectGroupManager
      >
    FTObjectGroupManager_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_ch.cpp:45

  class TAO_FT_Export FTObjectGroupManager
    : public virtual ::PortableGroup::ObjectGroupManager
  
  {
  public:
    friend class TAO::Narrow_Utils<FTObjectGroupManager>;

    // TAO_IDL - Generated from
    // .\be\be_type.cpp:307
    
    typedef FTObjectGroupManager_ptr _ptr_type;
    typedef FTObjectGroupManager_var _var_type;
    typedef FTObjectGroupManager_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static FTObjectGroupManager_ptr _duplicate (FTObjectGroupManager_ptr obj);

    static void _tao_release (FTObjectGroupManager_ptr obj);

    static FTObjectGroupManager_ptr _narrow (::CORBA::Object_ptr obj);
    static FTObjectGroupManager_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static FTObjectGroupManager_ptr _nil (void);

    virtual ::PortableGroup::ObjectGroup_ptr set_primary_member (
      ::PortableGroup::ObjectGroup_ptr object_group,
      const ::PortableGroup::Location & the_location);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_ch.cpp:156

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  private:
    TAO::Collocation_Proxy_Broker *the_TAO_FTObjectGroupManager_Proxy_Broker_;
  
  protected:
    // Concrete interface only.
    FTObjectGroupManager (void);

    // These methods traverse the inheritance tree and set the
    // parents piece of the given class in the right mode.
    virtual void FT_FTObjectGroupManager_setup_collocation (void);

    // Concrete non-local interface only.
    FTObjectGroupManager (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    FTObjectGroupManager (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);

    virtual ~FTObjectGroupManager (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    FTObjectGroupManager (const FTObjectGroupManager &);

    void operator= (const FTObjectGroupManager &);
  };

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:39

  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_FTObjectGroupManager;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const char *const FT_REPLICATION_STYLE = "org.omg.ft.ReplicationStyle";

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const char *const FT_CONSISTENCY_STYLE = "org.omg.ft.ConsistencyStyle";

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const char *const FT_MEMBERSHIP_STYLE = "org.omg.PortableGroup.MembershipStyle";

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long MEMB_APP_CTRL = 0;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const CORBA::Long MEMB_INF_CTRL = 1;

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const char *const FT_FAULT_MONITORING_STYLE = "org.omg.ft.FaultMonitoringStyle";

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const char *const FT_FAULT_MONITORING_GRANULARITY = "org.omg.ft.FaultMonitoringGranularity";

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const char *const FT_INITIAL_NUMBER_MEMBERS = "org.omg.PortableGroup.InitialNumberMembers";

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const char *const FT_MINIMUM_NUMBER_MEMBERS = "org.omg.PortableGroup.MinimumNumberMembers";

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const char *const FT_FACTORIES = "org.omg.PortableGroup.Factories";

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const char *const FT_FAULT_MONITORING_INTERVAL_AND_TIMEOUT = "org.omg.ft.FaultMonitoringIntervalAndTimeout";

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:41

  const char *const FT_CHECKPOINT_INTERVAL = "org.omg.ft.CheckpointInterval";

// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_module/module_ch.cpp:70

} // module FT

// TAO_IDL - Generated from
// .\be\be_visitor_arg_traits.cpp:68


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:147

#if !defined (_FT_FAULTNOTIFIER__ARG_TRAITS_)
#define _FT_FAULTNOTIFIER__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::FT::FaultNotifier>
    : public
        Object_Arg_Traits_T<
            ::FT::FaultNotifier_ptr,
            ::FT::FaultNotifier_var,
            ::FT::FaultNotifier_out,
            TAO::Objref_Traits<FT::FaultNotifier>,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::FT::FaultMonitoringIntervalAndTimeoutValue>
    : public
        Fixed_Size_Arg_Traits_T<
            ::FT::FaultMonitoringIntervalAndTimeoutValue,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:147

#if !defined (_FT_FTOBJECTGROUPMANAGER__ARG_TRAITS_)
#define _FT_FTOBJECTGROUPMANAGER__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::FT::FTObjectGroupManager>
    : public
        Object_Arg_Traits_T<
            ::FT::FTObjectGroupManager_ptr,
            ::FT::FTObjectGroupManager_var,
            ::FT::FTObjectGroupManager_out,
            TAO::Objref_Traits<FT::FTObjectGroupManager>,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// Proxy Broker Factory function pointer declarations.

// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_root/root_ch.cpp:204

extern TAO_FT_Export
TAO::Collocation_Proxy_Broker *
(*FT__TAO_FTObjectGroupManager_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj);

// TAO_IDL - Generated from
// .\be\be_visitor_traits.cpp:62


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_FT_FAULTNOTIFIER__TRAITS_)
#define _FT_FAULTNOTIFIER__TRAITS_

  template<>
  struct TAO_FT_Export Objref_Traits< ::FT::FaultNotifier>
  {
    static ::FT::FaultNotifier_ptr duplicate (
        ::FT::FaultNotifier_ptr p);
    static void release (
        ::FT::FaultNotifier_ptr p);
    static ::FT::FaultNotifier_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::FT::FaultNotifier_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_FT_FTOBJECTGROUPMANAGER__TRAITS_)
#define _FT_FTOBJECTGROUPMANAGER__TRAITS_

  template<>
  struct TAO_FT_Export Objref_Traits< ::FT::FTObjectGroupManager>
  {
    static ::FT::FTObjectGroupManager_ptr duplicate (
        ::FT::FTObjectGroupManager_ptr p);
    static void release (
        ::FT::FTObjectGroupManager_ptr p);
    static ::FT::FTObjectGroupManager_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::FT::FTObjectGroupManager_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface_fwd/any_op_ch.cpp:56



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace FT
{
  TAO_FT_Export void operator<<= ( ::CORBA::Any &, FaultNotifier_ptr); // copying
  TAO_FT_Export void operator<<= ( ::CORBA::Any &, FaultNotifier_ptr *); // non-copying
  TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, FaultNotifier *&);
}

#else



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_FT_Export void operator<<= (::CORBA::Any &, FT::FaultNotifier_ptr); // copying
TAO_FT_Export void operator<<= (::CORBA::Any &, FT::FaultNotifier_ptr *); // non-copying
TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, FT::FaultNotifier *&);
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_structure/any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace FT
{
  TAO_FT_Export void operator<<= (::CORBA::Any &, const ::FT::FaultMonitoringIntervalAndTimeoutValue &); // copying version
  TAO_FT_Export void operator<<= (::CORBA::Any &, ::FT::FaultMonitoringIntervalAndTimeoutValue*); // noncopying version
  TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::FT::FaultMonitoringIntervalAndTimeoutValue *&); // deprecated
TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::FT::FaultMonitoringIntervalAndTimeoutValue *&);
}

#else



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_FT_Export void operator<<= (::CORBA::Any &, const FT::FaultMonitoringIntervalAndTimeoutValue &); // copying version
TAO_FT_Export void operator<<= (::CORBA::Any &, FT::FaultMonitoringIntervalAndTimeoutValue*); // noncopying version
TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, FT::FaultMonitoringIntervalAndTimeoutValue *&); // deprecated
TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const FT::FaultMonitoringIntervalAndTimeoutValue *&);
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_exception/any_op_ch.cpp:44

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace FT
{
  

  TAO_FT_Export void operator<<= (::CORBA::Any &, const ::FT::BadReplicationStyle &); // copying version
  TAO_FT_Export void operator<<= (::CORBA::Any &, ::FT::BadReplicationStyle*); // noncopying version
  TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::FT::BadReplicationStyle *&); // deprecated
TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::FT::BadReplicationStyle *&);
}

#else



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



TAO_FT_Export void operator<<= (::CORBA::Any &, const FT::BadReplicationStyle &); // copying version
TAO_FT_Export void operator<<= (::CORBA::Any &, FT::BadReplicationStyle*); // noncopying version
TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, FT::BadReplicationStyle *&); // deprecated
TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const FT::BadReplicationStyle *&);
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_exception/any_op_ch.cpp:44

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace FT
{
  

  TAO_FT_Export void operator<<= (::CORBA::Any &, const ::FT::PrimaryNotSet &); // copying version
  TAO_FT_Export void operator<<= (::CORBA::Any &, ::FT::PrimaryNotSet*); // noncopying version
  TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::FT::PrimaryNotSet *&); // deprecated
TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::FT::PrimaryNotSet *&);
}

#else



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



TAO_FT_Export void operator<<= (::CORBA::Any &, const FT::PrimaryNotSet &); // copying version
TAO_FT_Export void operator<<= (::CORBA::Any &, FT::PrimaryNotSet*); // noncopying version
TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, FT::PrimaryNotSet *&); // deprecated
TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const FT::PrimaryNotSet *&);
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/any_op_ch.cpp:46



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace FT
{
  TAO_FT_Export void operator<<= ( ::CORBA::Any &, FTObjectGroupManager_ptr); // copying
  TAO_FT_Export void operator<<= ( ::CORBA::Any &, FTObjectGroupManager_ptr *); // non-copying
  TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, FTObjectGroupManager_ptr &);
}

#else



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_FT_Export void operator<<= (::CORBA::Any &, FT::FTObjectGroupManager_ptr); // copying
TAO_FT_Export void operator<<= (::CORBA::Any &, FT::FTObjectGroupManager_ptr *); // non-copying
TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, FT::FTObjectGroupManager_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface_fwd/cdr_op_ch.cpp:55



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_FT_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const FT::FaultNotifier_ptr );
TAO_FT_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, FT::FaultNotifier_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_structure/cdr_op_ch.cpp:45



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_FT_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const FT::FaultMonitoringIntervalAndTimeoutValue &);
TAO_FT_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, FT::FaultMonitoringIntervalAndTimeoutValue &);

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_exception/cdr_op_ch.cpp:43

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



TAO_FT_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const FT::BadReplicationStyle &);
TAO_FT_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, FT::BadReplicationStyle &);

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_exception/cdr_op_ch.cpp:43

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



TAO_FT_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const FT::PrimaryNotSet &);
TAO_FT_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, FT::PrimaryNotSet &);

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/cdr_op_ch.cpp:47


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_FT_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const FT::FTObjectGroupManager_ptr );
TAO_FT_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, FT::FTObjectGroupManager_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// .\be\be_codegen.cpp:1581


TAO_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "FT_CORBAC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

