// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.0a
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:460

#ifndef _TAO_IDL_PORTABLEGROUPS_TFQO1U_H_
#define _TAO_IDL_PORTABLEGROUPS_TFQO1U_H_


#include "PortableGroupC.h"
#include "tao/PortableServer/PortableServer_includeS.h"
#include "tao/OctetSeqS.h"
#include "tao/orb_typesS.h"
#include "tao/PolicyS.h"
#include "tao/UShortSeqS.h"
#include "CosNamingS.h"
#include "tao/IOPS.h"
#include "tao/GIOPS.h"
#include "tao/BooleanSeqS.h"
#include "tao/CharSeqS.h"
#include "tao/DoubleSeqS.h"
#include "tao/FloatSeqS.h"
#include "tao/LongDoubleSeqS.h"
#include "tao/LongSeqS.h"
#include "tao/ShortSeqS.h"
#include "tao/StringSeqS.h"
#include "tao/ULongSeqS.h"
#include "tao/WCharSeqS.h"
#include "tao/WStringSeqS.h"
#include "tao/LongLongSeqS.h"
#include "tao/ULongLongSeqS.h"
#include "tao/Policy_ManagerS.h"
#include "tao/Policy_CurrentS.h"
#include "tao/ServicesS.h"
#include "tao/ParameterModeS.h"
#include "tao/Typecode_typesS.h"
#include "tao/WrongTransactionS.h"
#include "PortableGroup_Simple_DSS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/Any_SArg_Traits.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/Messaging/MessagingS.h"
#include "tao/Collocation_Proxy_Broker.h"
#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// .\be\be_visitor_arg_traits.cpp:68


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:308

#if !defined (_MESSAGING_EXCEPTIONHOLDER__SARG_TRAITS_)
#define _MESSAGING_EXCEPTIONHOLDER__SARG_TRAITS_

  template<>
  class SArg_Traits< ::Messaging::ExceptionHolder>
    : public
        Object_SArg_Traits_T<
            ::Messaging::ExceptionHolder *,
            ::Messaging::ExceptionHolder_var,
            ::Messaging::ExceptionHolder_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::PortableGroup::GroupIIOPProfile>
    : public
        Var_Size_SArg_Traits_T<
            ::PortableGroup::GroupIIOPProfile,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:147

#if !defined (_PORTABLEGROUP_GENERICFACTORY__SARG_TRAITS_)
#define _PORTABLEGROUP_GENERICFACTORY__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::PortableGroup::GenericFactory>
    : public
        Object_SArg_Traits_T<
            ::PortableGroup::GenericFactory_ptr,
            ::PortableGroup::GenericFactory_var,
            ::PortableGroup::GenericFactory_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::PortableGroup::ObjectGroups>
    : public
        Var_Size_SArg_Traits_T<
            ::PortableGroup::ObjectGroups,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::PortableGroup::Property>
    : public
        Var_Size_SArg_Traits_T<
            ::PortableGroup::Property,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::PortableGroup::Properties>
    : public
        Var_Size_SArg_Traits_T<
            ::PortableGroup::Properties,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::PortableGroup::Locations>
    : public
        Var_Size_SArg_Traits_T<
            ::PortableGroup::Locations,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:941

  template<>
  class SArg_Traits< ::PortableGroup::FactoryInfo>
    : public
        Var_Size_SArg_Traits_T<
            ::PortableGroup::FactoryInfo,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::PortableGroup::FactoryInfos>
    : public
        Var_Size_SArg_Traits_T<
            ::PortableGroup::FactoryInfos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:147

#if !defined (_PORTABLEGROUP_PROPERTYMANAGER__SARG_TRAITS_)
#define _PORTABLEGROUP_PROPERTYMANAGER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::PortableGroup::PropertyManager>
    : public
        Object_SArg_Traits_T<
            ::PortableGroup::PropertyManager_ptr,
            ::PortableGroup::PropertyManager_var,
            ::PortableGroup::PropertyManager_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:147

#if !defined (_PORTABLEGROUP_AMI_PROPERTYMANAGERHANDLER__SARG_TRAITS_)
#define _PORTABLEGROUP_AMI_PROPERTYMANAGERHANDLER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::PortableGroup::AMI_PropertyManagerHandler>
    : public
        Object_SArg_Traits_T<
            ::PortableGroup::AMI_PropertyManagerHandler_ptr,
            ::PortableGroup::AMI_PropertyManagerHandler_var,
            ::PortableGroup::AMI_PropertyManagerHandler_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:147

#if !defined (_PORTABLEGROUP_OBJECTGROUPMANAGER__SARG_TRAITS_)
#define _PORTABLEGROUP_OBJECTGROUPMANAGER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::PortableGroup::ObjectGroupManager>
    : public
        Object_SArg_Traits_T<
            ::PortableGroup::ObjectGroupManager_ptr,
            ::PortableGroup::ObjectGroupManager_var,
            ::PortableGroup::ObjectGroupManager_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:147

#if !defined (_PORTABLEGROUP_AMI_OBJECTGROUPMANAGERHANDLER__SARG_TRAITS_)
#define _PORTABLEGROUP_AMI_OBJECTGROUPMANAGERHANDLER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::PortableGroup::AMI_ObjectGroupManagerHandler>
    : public
        Object_SArg_Traits_T<
            ::PortableGroup::AMI_ObjectGroupManagerHandler_ptr,
            ::PortableGroup::AMI_ObjectGroupManagerHandler_var,
            ::PortableGroup::AMI_ObjectGroupManagerHandler_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:147

#if !defined (_PORTABLEGROUP_AMI_GENERICFACTORYHANDLER__SARG_TRAITS_)
#define _PORTABLEGROUP_AMI_GENERICFACTORYHANDLER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::PortableGroup::AMI_GenericFactoryHandler>
    : public
        Object_SArg_Traits_T<
            ::PortableGroup::AMI_GenericFactoryHandler_ptr,
            ::PortableGroup::AMI_GenericFactoryHandler_var,
            ::PortableGroup::AMI_GenericFactoryHandler_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:147

#if !defined (_PORTABLEGROUP_FACTORYREGISTRY__SARG_TRAITS_)
#define _PORTABLEGROUP_FACTORYREGISTRY__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::PortableGroup::FactoryRegistry>
    : public
        Object_SArg_Traits_T<
            ::PortableGroup::FactoryRegistry_ptr,
            ::PortableGroup::FactoryRegistry_var,
            ::PortableGroup::FactoryRegistry_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:147

#if !defined (_PORTABLEGROUP_AMI_FACTORYREGISTRYHANDLER__SARG_TRAITS_)
#define _PORTABLEGROUP_AMI_FACTORYREGISTRYHANDLER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::PortableGroup::AMI_FactoryRegistryHandler>
    : public
        Object_SArg_Traits_T<
            ::PortableGroup::AMI_FactoryRegistryHandler_ptr,
            ::PortableGroup::AMI_FactoryRegistryHandler_var,
            ::PortableGroup::AMI_FactoryRegistryHandler_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:147

#if !defined (_PORTABLEGROUP_TAO_UPDATEOBJECTGROUP__SARG_TRAITS_)
#define _PORTABLEGROUP_TAO_UPDATEOBJECTGROUP__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::PortableGroup::TAO_UpdateObjectGroup>
    : public
        Object_SArg_Traits_T<
            ::PortableGroup::TAO_UpdateObjectGroup_ptr,
            ::PortableGroup::TAO_UpdateObjectGroup_var,
            ::PortableGroup::TAO_UpdateObjectGroup_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:147

#if !defined (_PORTABLEGROUP_AMI_TAO_UPDATEOBJECTGROUPHANDLER__SARG_TRAITS_)
#define _PORTABLEGROUP_AMI_TAO_UPDATEOBJECTGROUPHANDLER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::PortableGroup::AMI_TAO_UpdateObjectGroupHandler>
    : public
        Object_SArg_Traits_T<
            ::PortableGroup::AMI_TAO_UpdateObjectGroupHandler_ptr,
            ::PortableGroup::AMI_TAO_UpdateObjectGroupHandler_var,
            ::PortableGroup::AMI_TAO_UpdateObjectGroupHandler_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // .\be\be_visitor_arg_traits.cpp:679

  template<>
  class SArg_Traits< ::PortableGroup::IDs>
    : public
        Var_Size_SArg_Traits_T<
            ::PortableGroup::IDs,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_module/module_sh.cpp:41

namespace POA_PortableGroup
{
  

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_sh.cpp:78

  class PropertyManager;
  typedef PropertyManager *PropertyManager_ptr;

  class TAO_PortableGroup_Export PropertyManager
    : public virtual PortableServer::ServantBase
  {
  protected:
    PropertyManager (void);
  
  public:
    /// Useful for template programming.
    typedef ::PortableGroup::PropertyManager _stub_type;
    typedef ::PortableGroup::PropertyManager_ptr _stub_ptr_type;
    typedef ::PortableGroup::PropertyManager_var _stub_var_type;

    PropertyManager (const PropertyManager& rhs);
    virtual ~PropertyManager (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::PortableGroup::PropertyManager *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void set_default_properties (
      const ::PortableGroup::Properties & props) = 0;

    static void set_default_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::PortableGroup::Properties * get_default_properties (
      void) = 0;

    static void get_default_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void remove_default_properties (
      const ::PortableGroup::Properties & props) = 0;

    static void remove_default_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void set_type_properties (
      const char * type_id,
      const ::PortableGroup::Properties & overrides) = 0;

    static void set_type_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::PortableGroup::Properties * get_type_properties (
      const char * type_id) = 0;

    static void get_type_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void remove_type_properties (
      const char * type_id,
      const ::PortableGroup::Properties & props) = 0;

    static void remove_type_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void set_properties_dynamically (
      ::PortableGroup::ObjectGroup_ptr object_group,
      const ::PortableGroup::Properties & overrides) = 0;

    static void set_properties_dynamically_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::PortableGroup::Properties * get_properties (
      ::PortableGroup::ObjectGroup_ptr object_group) = 0;

    static void get_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);
  };

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_sh.cpp:78

  class AMI_PropertyManagerHandler;
  typedef AMI_PropertyManagerHandler *AMI_PropertyManagerHandler_ptr;

  class TAO_PortableGroup_Export AMI_PropertyManagerHandler
    : public virtual POA_Messaging::ReplyHandler
  {
  protected:
    AMI_PropertyManagerHandler (void);
  
  public:
    /// Useful for template programming.
    typedef ::PortableGroup::AMI_PropertyManagerHandler _stub_type;
    typedef ::PortableGroup::AMI_PropertyManagerHandler_ptr _stub_ptr_type;
    typedef ::PortableGroup::AMI_PropertyManagerHandler_var _stub_var_type;

    AMI_PropertyManagerHandler (const AMI_PropertyManagerHandler& rhs);
    virtual ~AMI_PropertyManagerHandler (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::PortableGroup::AMI_PropertyManagerHandler *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void set_default_properties (
      void) = 0;

    static void set_default_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void set_default_properties_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void set_default_properties_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_default_properties (
      const ::PortableGroup::Properties & ami_return_val) = 0;

    static void get_default_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_default_properties_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void get_default_properties_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void remove_default_properties (
      void) = 0;

    static void remove_default_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void remove_default_properties_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void remove_default_properties_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void set_type_properties (
      void) = 0;

    static void set_type_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void set_type_properties_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void set_type_properties_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_type_properties (
      const ::PortableGroup::Properties & ami_return_val) = 0;

    static void get_type_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_type_properties_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void get_type_properties_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void remove_type_properties (
      void) = 0;

    static void remove_type_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void remove_type_properties_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void remove_type_properties_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void set_properties_dynamically (
      void) = 0;

    static void set_properties_dynamically_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void set_properties_dynamically_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void set_properties_dynamically_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_properties (
      const ::PortableGroup::Properties & ami_return_val) = 0;

    static void get_properties_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_properties_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void get_properties_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);
  };

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_sh.cpp:78

  class ObjectGroupManager;
  typedef ObjectGroupManager *ObjectGroupManager_ptr;

  class TAO_PortableGroup_Export ObjectGroupManager
    : public virtual PortableServer::ServantBase
  {
  protected:
    ObjectGroupManager (void);
  
  public:
    /// Useful for template programming.
    typedef ::PortableGroup::ObjectGroupManager _stub_type;
    typedef ::PortableGroup::ObjectGroupManager_ptr _stub_ptr_type;
    typedef ::PortableGroup::ObjectGroupManager_var _stub_var_type;

    ObjectGroupManager (const ObjectGroupManager& rhs);
    virtual ~ObjectGroupManager (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::PortableGroup::ObjectGroupManager *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::PortableGroup::ObjectGroup_ptr create_member (
      ::PortableGroup::ObjectGroup_ptr object_group,
      const ::PortableGroup::Location & the_location,
      const char * type_id,
      const ::PortableGroup::Criteria & the_criteria) = 0;

    static void create_member_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::PortableGroup::ObjectGroup_ptr add_member (
      ::PortableGroup::ObjectGroup_ptr object_group,
      const ::PortableGroup::Location & the_location,
      ::CORBA::Object_ptr member) = 0;

    static void add_member_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::PortableGroup::ObjectGroup_ptr remove_member (
      ::PortableGroup::ObjectGroup_ptr object_group,
      const ::PortableGroup::Location & the_location) = 0;

    static void remove_member_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::PortableGroup::Locations * locations_of_members (
      ::PortableGroup::ObjectGroup_ptr object_group) = 0;

    static void locations_of_members_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::PortableGroup::ObjectGroups * groups_at_location (
      const ::PortableGroup::Location & the_location) = 0;

    static void groups_at_location_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::PortableGroup::ObjectGroupId get_object_group_id (
      ::PortableGroup::ObjectGroup_ptr object_group) = 0;

    static void get_object_group_id_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::PortableGroup::ObjectGroup_ptr get_object_group_ref (
      ::PortableGroup::ObjectGroup_ptr object_group) = 0;

    static void get_object_group_ref_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::CORBA::Object_ptr get_member_ref (
      ::PortableGroup::ObjectGroup_ptr object_group,
      const ::PortableGroup::Location & loc) = 0;

    static void get_member_ref_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::PortableGroup::ObjectGroup_ptr get_object_group_ref_from_id (
      ::PortableGroup::ObjectGroupId group_id) = 0;

    static void get_object_group_ref_from_id_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);
  };

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_sh.cpp:78

  class AMI_ObjectGroupManagerHandler;
  typedef AMI_ObjectGroupManagerHandler *AMI_ObjectGroupManagerHandler_ptr;

  class TAO_PortableGroup_Export AMI_ObjectGroupManagerHandler
    : public virtual POA_Messaging::ReplyHandler
  {
  protected:
    AMI_ObjectGroupManagerHandler (void);
  
  public:
    /// Useful for template programming.
    typedef ::PortableGroup::AMI_ObjectGroupManagerHandler _stub_type;
    typedef ::PortableGroup::AMI_ObjectGroupManagerHandler_ptr _stub_ptr_type;
    typedef ::PortableGroup::AMI_ObjectGroupManagerHandler_var _stub_var_type;

    AMI_ObjectGroupManagerHandler (const AMI_ObjectGroupManagerHandler& rhs);
    virtual ~AMI_ObjectGroupManagerHandler (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::PortableGroup::AMI_ObjectGroupManagerHandler *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void create_member (
      ::PortableGroup::ObjectGroup_ptr ami_return_val) = 0;

    static void create_member_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void create_member_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void create_member_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void add_member (
      ::PortableGroup::ObjectGroup_ptr ami_return_val) = 0;

    static void add_member_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void add_member_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void add_member_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void remove_member (
      ::PortableGroup::ObjectGroup_ptr ami_return_val) = 0;

    static void remove_member_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void remove_member_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void remove_member_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void locations_of_members (
      const ::PortableGroup::Locations & ami_return_val) = 0;

    static void locations_of_members_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void locations_of_members_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void locations_of_members_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void groups_at_location (
      const ::PortableGroup::ObjectGroups & ami_return_val) = 0;

    static void groups_at_location_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void groups_at_location_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void groups_at_location_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_object_group_id (
      ::PortableGroup::ObjectGroupId ami_return_val) = 0;

    static void get_object_group_id_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_object_group_id_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void get_object_group_id_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_object_group_ref (
      ::PortableGroup::ObjectGroup_ptr ami_return_val) = 0;

    static void get_object_group_ref_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_object_group_ref_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void get_object_group_ref_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_member_ref (
      ::CORBA::Object_ptr ami_return_val) = 0;

    static void get_member_ref_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_member_ref_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void get_member_ref_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_object_group_ref_from_id (
      ::PortableGroup::ObjectGroup_ptr ami_return_val) = 0;

    static void get_object_group_ref_from_id_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void get_object_group_ref_from_id_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void get_object_group_ref_from_id_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);
  };

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_sh.cpp:78

  class GenericFactory;
  typedef GenericFactory *GenericFactory_ptr;

  class TAO_PortableGroup_Export GenericFactory
    : public virtual PortableServer::ServantBase
  {
  protected:
    GenericFactory (void);
  
  public:
    /// Useful for template programming.
    typedef ::PortableGroup::GenericFactory _stub_type;
    typedef ::PortableGroup::GenericFactory_ptr _stub_ptr_type;
    typedef ::PortableGroup::GenericFactory_var _stub_var_type;

    GenericFactory (const GenericFactory& rhs);
    virtual ~GenericFactory (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::PortableGroup::GenericFactory *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::CORBA::Object_ptr create_object (
      const char * type_id,
      const ::PortableGroup::Criteria & the_criteria,
      ::PortableGroup::GenericFactory::FactoryCreationId_out factory_creation_id) = 0;

    static void create_object_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void delete_object (
      const ::PortableGroup::GenericFactory::FactoryCreationId & factory_creation_id) = 0;

    static void delete_object_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);
  };

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_sh.cpp:78

  class AMI_GenericFactoryHandler;
  typedef AMI_GenericFactoryHandler *AMI_GenericFactoryHandler_ptr;

  class TAO_PortableGroup_Export AMI_GenericFactoryHandler
    : public virtual POA_Messaging::ReplyHandler
  {
  protected:
    AMI_GenericFactoryHandler (void);
  
  public:
    /// Useful for template programming.
    typedef ::PortableGroup::AMI_GenericFactoryHandler _stub_type;
    typedef ::PortableGroup::AMI_GenericFactoryHandler_ptr _stub_ptr_type;
    typedef ::PortableGroup::AMI_GenericFactoryHandler_var _stub_var_type;

    AMI_GenericFactoryHandler (const AMI_GenericFactoryHandler& rhs);
    virtual ~AMI_GenericFactoryHandler (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::PortableGroup::AMI_GenericFactoryHandler *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void create_object (
      ::CORBA::Object_ptr ami_return_val,
      const ::PortableGroup::GenericFactory::FactoryCreationId & factory_creation_id) = 0;

    static void create_object_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void create_object_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void create_object_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void delete_object (
      void) = 0;

    static void delete_object_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void delete_object_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void delete_object_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);
  };

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_sh.cpp:78

  class FactoryRegistry;
  typedef FactoryRegistry *FactoryRegistry_ptr;

  class TAO_PortableGroup_Export FactoryRegistry
    : public virtual PortableServer::ServantBase
  {
  protected:
    FactoryRegistry (void);
  
  public:
    /// Useful for template programming.
    typedef ::PortableGroup::FactoryRegistry _stub_type;
    typedef ::PortableGroup::FactoryRegistry_ptr _stub_ptr_type;
    typedef ::PortableGroup::FactoryRegistry_var _stub_var_type;

    FactoryRegistry (const FactoryRegistry& rhs);
    virtual ~FactoryRegistry (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::PortableGroup::FactoryRegistry *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void register_factory (
      const char * role,
      const char * type_id,
      const ::PortableGroup::FactoryInfo & factory_info) = 0;

    static void register_factory_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void unregister_factory (
      const char * role,
      const ::PortableGroup::Location & the_location) = 0;

    static void unregister_factory_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void unregister_factory_by_role (
      const char * role) = 0;

    static void unregister_factory_by_role_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void unregister_factory_by_location (
      const ::PortableGroup::Location & the_location) = 0;

    static void unregister_factory_by_location_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::PortableGroup::FactoryInfos * list_factories_by_role (
      const char * role,
      ::CORBA::String_out type_id) = 0;

    static void list_factories_by_role_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual ::PortableGroup::FactoryInfos * list_factories_by_location (
      const ::PortableGroup::Location & the_location) = 0;

    static void list_factories_by_location_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);
  };

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_sh.cpp:78

  class AMI_FactoryRegistryHandler;
  typedef AMI_FactoryRegistryHandler *AMI_FactoryRegistryHandler_ptr;

  class TAO_PortableGroup_Export AMI_FactoryRegistryHandler
    : public virtual POA_Messaging::ReplyHandler
  {
  protected:
    AMI_FactoryRegistryHandler (void);
  
  public:
    /// Useful for template programming.
    typedef ::PortableGroup::AMI_FactoryRegistryHandler _stub_type;
    typedef ::PortableGroup::AMI_FactoryRegistryHandler_ptr _stub_ptr_type;
    typedef ::PortableGroup::AMI_FactoryRegistryHandler_var _stub_var_type;

    AMI_FactoryRegistryHandler (const AMI_FactoryRegistryHandler& rhs);
    virtual ~AMI_FactoryRegistryHandler (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::PortableGroup::AMI_FactoryRegistryHandler *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void register_factory (
      void) = 0;

    static void register_factory_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void register_factory_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void register_factory_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void unregister_factory (
      void) = 0;

    static void unregister_factory_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void unregister_factory_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void unregister_factory_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void unregister_factory_by_role (
      void) = 0;

    static void unregister_factory_by_role_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void unregister_factory_by_role_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void unregister_factory_by_role_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void unregister_factory_by_location (
      void) = 0;

    static void unregister_factory_by_location_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void unregister_factory_by_location_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void unregister_factory_by_location_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void list_factories_by_role (
      const ::PortableGroup::FactoryInfos & ami_return_val,
      const char * type_id) = 0;

    static void list_factories_by_role_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void list_factories_by_role_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void list_factories_by_role_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void list_factories_by_location (
      const ::PortableGroup::FactoryInfos & ami_return_val) = 0;

    static void list_factories_by_location_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void list_factories_by_location_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void list_factories_by_location_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);
  };

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_sh.cpp:78

  class TAO_UpdateObjectGroup;
  typedef TAO_UpdateObjectGroup *TAO_UpdateObjectGroup_ptr;

  class TAO_PortableGroup_Export TAO_UpdateObjectGroup
    : public virtual PortableServer::ServantBase
  {
  protected:
    TAO_UpdateObjectGroup (void);
  
  public:
    /// Useful for template programming.
    typedef ::PortableGroup::TAO_UpdateObjectGroup _stub_type;
    typedef ::PortableGroup::TAO_UpdateObjectGroup_ptr _stub_ptr_type;
    typedef ::PortableGroup::TAO_UpdateObjectGroup_var _stub_var_type;

    TAO_UpdateObjectGroup (const TAO_UpdateObjectGroup& rhs);
    virtual ~TAO_UpdateObjectGroup (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::PortableGroup::TAO_UpdateObjectGroup *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void tao_update_object_group (
      const char * iogr,
      ::PortableGroup::ObjectGroupRefVersion version,
      ::CORBA::Boolean is_primary) = 0;

    static void tao_update_object_group_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);
  };

  // TAO_IDL - Generated from
  // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_sh.cpp:78

  class AMI_TAO_UpdateObjectGroupHandler;
  typedef AMI_TAO_UpdateObjectGroupHandler *AMI_TAO_UpdateObjectGroupHandler_ptr;

  class TAO_PortableGroup_Export AMI_TAO_UpdateObjectGroupHandler
    : public virtual POA_Messaging::ReplyHandler
  {
  protected:
    AMI_TAO_UpdateObjectGroupHandler (void);
  
  public:
    /// Useful for template programming.
    typedef ::PortableGroup::AMI_TAO_UpdateObjectGroupHandler _stub_type;
    typedef ::PortableGroup::AMI_TAO_UpdateObjectGroupHandler_ptr _stub_ptr_type;
    typedef ::PortableGroup::AMI_TAO_UpdateObjectGroupHandler_var _stub_var_type;

    AMI_TAO_UpdateObjectGroupHandler (const AMI_TAO_UpdateObjectGroupHandler& rhs);
    virtual ~AMI_TAO_UpdateObjectGroupHandler (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    static void _is_a_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _non_existent_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _interface_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _component_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    static void _repository_id_skel (
        TAO_ServerRequest & req,
        void * servant_upcall,
        void * servant);
    
    virtual void _dispatch (
        TAO_ServerRequest & req,
        void * servant_upcall);
    
    ::PortableGroup::AMI_TAO_UpdateObjectGroupHandler *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void tao_update_object_group (
      void) = 0;

    static void tao_update_object_group_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);

    // TAO_IDL - Generated from
    // e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:41

    virtual void tao_update_object_group_excep (
      ::Messaging::ExceptionHolder * excep_holder) = 0;

    static void tao_update_object_group_excep_skel (
        TAO_ServerRequest & server_request,
        void * servant_upcall,
        void * servant);
  };

// TAO_IDL - Generated from
// e:\sca\ace_diab\ace_wrappers\tao\tao_idl\be\be_visitor_module/module_sh.cpp:72

} // module PortableGroup

TAO_END_VERSIONED_NAMESPACE_DECL


#if defined (__ACE_INLINE__)
#include "PortableGroupS.inl"
#endif /* defined INLINE */

#endif /* ifndef */

