// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.0a
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:375


#include "DynamicC.h"
#include "tao/CDR.h"

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from 
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_sequence/sequence_cs.cpp:65

#if !defined (_DYNAMIC_PARAMETERLIST_CS_)
#define _DYNAMIC_PARAMETERLIST_CS_

Dynamic::ParameterList::ParameterList (void)
{}

Dynamic::ParameterList::ParameterList (
    ::CORBA::ULong max)
  : ::TAO::unbounded_value_sequence<
        Parameter
      > (max)
{}

Dynamic::ParameterList::ParameterList (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    Dynamic::Parameter * buffer,
    ::CORBA::Boolean release
  )
  : ::TAO::unbounded_value_sequence<
        Parameter
      >
    (max, length, buffer, release)
{}

Dynamic::ParameterList::ParameterList (
    const ParameterList &seq)
  : ::TAO::unbounded_value_sequence<
        Parameter
      > (seq)
{}

Dynamic::ParameterList::~ParameterList (void)
{}

void Dynamic::ParameterList::_tao_any_destructor (
    void * _tao_void_pointer)
{
  ParameterList * _tao_tmp_pointer =
    static_cast<ParameterList *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

#endif /* end #if !defined */

// TAO_IDL - Generated from 
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_sequence/sequence_cs.cpp:65

#if !defined (_DYNAMIC_EXCEPTIONLIST_CS_)
#define _DYNAMIC_EXCEPTIONLIST_CS_

Dynamic::ExceptionList::ExceptionList (void)
{}

Dynamic::ExceptionList::ExceptionList (
    ::CORBA::ULong max)
  : ::TAO::unbounded_object_reference_sequence<
        ::CORBA::TypeCode,
        ::CORBA::TypeCode_var
      > (max)
{}

Dynamic::ExceptionList::ExceptionList (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    ::CORBA::TypeCode_ptr * buffer,
    ::CORBA::Boolean release
  )
  : ::TAO::unbounded_object_reference_sequence<
        ::CORBA::TypeCode,
        ::CORBA::TypeCode_var
      >
    (max, length, buffer, release)
{}

Dynamic::ExceptionList::ExceptionList (
    const ExceptionList &seq)
  : ::TAO::unbounded_object_reference_sequence<
        ::CORBA::TypeCode,
        ::CORBA::TypeCode_var
      > (seq)
{}

Dynamic::ExceptionList::~ExceptionList (void)
{}

void Dynamic::ExceptionList::_tao_any_destructor (
    void * _tao_void_pointer)
{
  ExceptionList * _tao_tmp_pointer =
    static_cast<ExceptionList *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_sequence/cdr_op_cs.cpp:90
#if !defined _TAO_CDR_OP_Dynamic_ParameterList_CPP_
#define _TAO_CDR_OP_Dynamic_ParameterList_CPP_


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Dynamic::ParameterList &_tao_sequence)
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Dynamic::ParameterList &_tao_sequence)
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


#endif /* _TAO_CDR_OP_Dynamic_ParameterList_CPP_ */

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_sequence/cdr_op_cs.cpp:90
#if !defined _TAO_CDR_OP_Dynamic_ExceptionList_CPP_
#define _TAO_CDR_OP_Dynamic_ExceptionList_CPP_


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Dynamic::ExceptionList &_tao_sequence)
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Dynamic::ExceptionList &_tao_sequence)
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


#endif /* _TAO_CDR_OP_Dynamic_ExceptionList_CPP_ */


TAO_END_VERSIONED_NAMESPACE_DECL


