/***************************************************************************//**
* @file     PortTypes.idl
* @author   open Team
* @version  9
* @date     2017-03-10
* @brief
* @Remark : <Description>
* @verbatim
* ==============================================================================
* <Date>     | <Version> | <Author>       | <Description>
* ==============================================================================
*  2015-05-23 | 1       | open Team       | Create file
* ==============================================================================
* @endverbatim
* ******************************************************************************
* <h2><center>&copy; Copyright(c)2015-2025 JFounder Info Tech Co.,Ltd</center></h2>
* All rights reserved. The right to copy, distribute, modify or otherwise make use
* of this software may be licensed only pursuant to the terms of an applicable
* JFounder license agreement. Company website: www.onetek.net
*//****************************************************************************/

#ifndef __PORTTYPES_DEFINED
#define __PORTTYPES_DEFINED

module PortTypes {
	typedef sequence <wstring> WstringSequence;
	
	typedef sequence <boolean> BooleanSequence;

	typedef sequence <char> CharSequence;

	typedef sequence <double> DoubleSequence;

	typedef sequence <long double> LongDoubleSequence;

	typedef sequence <long long> LongLongSequence;

	typedef sequence <long> LongSequence;

	typedef sequence <short> ShortSequence;

	typedef sequence <unsigned long long> UlongLongSequence;

	typedef sequence <unsigned long> UlongSequence;

	typedef sequence <unsigned short> UshortSequence;

	typedef sequence <wchar> WcharSequence;

	typedef sequence <float> FloatSequence;
};
#endif
